travis:
  secure:
    BINSTAR_TOKEN: T9k/FE5Ehp10ANK4XH/bNCHducXSl8LPDQ0Mu2O4Rmpw9/FUQSuwemEB53fcswvvwdgsg7Dhiif6D/WoLjW4xn1vafwR+fmMnnNerVJ3MMCLKoepmUlACR/o4gOYScTaz3/xjQhJ3SnQh4U8rnKggXrnL2shMNNPxVDB6qV8M8TnJzFIPtLnUAWY+IMpFpnY12rFqhWuPiWNcW/HlQhGwb3d7qshbXsGjahKRruandm97Wk5DAwRBFrzX0aHtj7dFMplLLgVn1NMRa3jxkCDc1O1f55LbF8B60yeHI/lLdw709TVoSb1qD+FyvyiGsoQaf6mtFBqheZ7lw3rjmuOPGp5G04lyxq2T56TM/CfTz8F2HpBkw2U/yyELNlxQ99cDn+1OOOuhDWJY78wOLg9LP659yLKXEJlmeQ3taawmlqFtpO1dOXmHpzHTEzR3P4WN8aDG2GUHvFTu6O3ruz8SdNTBatRoc6uhA+d8417IaoDAd9s/sK5qOzZrfm8b70feMW6YyWfzN/qlvkbmZOgKOVB4qn+FT8GadDdJbbZNVpNzsEDdwRrBChpsG0kL4OHW1xPSoXyflcGBAts5LYlbBZcZXkjljd4HKGd+YNmTHiuu5SDrfyqzsDX9aLEJwc2lW8Ur/SPpEPH06SvDFGziCXI3wrT/jK2lVxN+UHi7Xg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
